name: Update Mihomo Proxy Config

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every 24 hours
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-sublist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Update Proxy Configs
        run: |
          import os
          import yaml

          url_file = "Simple_URL_List.txt"
          template_file = "mihomo_template.txt"
          output_dir = "Sublist"
          cache_file = ".last_urls.txt"

          if not os.path.exists(output_dir):
              os.makedirs(output_dir)

          # Read previous URLs to detect changes
          previous = {}
          if os.path.exists(cache_file):
              with open(cache_file, "r") as f:
                  for line in f:
                      name, old_url = line.strip().split("|", 1)
                      previous[name] = old_url

          new_cache = []
          changes_detected = False

          with open(url_file, "r") as f:
              lines = [line.strip() for line in f if line.strip()]

          for line in lines:
              if "|" not in line:
                  continue
              filename, new_url = line.split("|", 1)
              old_url = previous.get(filename)
              new_cache.append(f"{filename}|{new_url}")

              if new_url != old_url:
                  changes_detected = True
                  with open(template_file, "r") as tf:
                      data = yaml.safe_load(tf)

                  data["proxy-providers"]["proxy"]["url"] = new_url

                  output_path = os.path.join(output_dir, filename)
                  with open(output_path, "w") as outf:
                      yaml.dump(data, outf, default_flow_style=False)

          # Update cache
          with open(cache_file, "w") as f:
              f.write("\n".join(new_cache))

          if not changes_detected:
              print("No changes detected in URLs.")

        shell: python

      - name: Commit & Push if Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Sublist/ .last_urls.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Sublist configs from Simple_URL_List.txt"
          git push
