name: به‌روزرسانی Sublist

on:
  schedule:
    - cron: '0 0 * * *'  # زمان‌بندی اجرای خودکار
  workflow_dispatch:  # امکان اجرای دستی

permissions:
  contents: write

jobs:
  update-sublist:
    runs-on: ubuntu-latest

    steps:
      - name: کلون کردن ریپو
        uses: actions/checkout@v3

      - name: نصب پایتون و PyYAML
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip install pyyaml

      - name: اجرای اسکریپت پایتون
        run: |
          python3 update_sublist.py

      - name: Commit و Push در صورت وجود تغییر
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Sublist/ .last_urls.txt || true
          git diff --cached --quiet || git commit -m "🔁 به‌روزرسانی Sublist از Simple_URL_List.txt"
          git push
