name: به‌روزرسانی Sublist

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت ۰۰:۰۰ UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-sublist:
    runs-on: ubuntu-latest

    steps:
      - name: کلون کردن ریپو
        uses: actions/checkout@v3

      - name: نصب پایتون و ruamel.yaml
        run: |
          python3 -m pip install --upgrade pip
          pip install ruamel.yaml

      - name: اجرای اسکریپت Python
        run: python3 update_sublist.py

      - name: Commit و Push در صورت تغییر
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Sublist/ .last_urls.txt || true
          git diff --cached --quiet || git commit -m "🔁 به‌روزرسانی Sublist از Simple_URL_List.txt"
          git push
