name: به‌روزرسانی Sublist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-sublist:
    runs-on: ubuntu-latest

    steps:
      - name: کلون کردن ریپو
        uses: actions/checkout@v3

      - name: نصب پایتون
        run: |
          python3 -m pip install --upgrade pip

      - name: اجرای اسکریپت Python
        run: python3 update_sublist.py

      - name: Commit و Push در صورت تغییر
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # افزودن فایل‌ها با مدیریت خطا
          git add --ignore-errors Sublist/ .cache_simple.txt .cache_complex.txt .last_template_mtime README.md
          
          # Commit فقط در صورت وجود تغییرات
          git diff --cached --quiet || {
            git commit -m "🔁 به‌روزرسانی خودکار فایل‌ها"
            git push
          }
