name: به‌روزرسانی Sublist

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت ۰۰:۰۰ UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-sublist:
    runs-on: ubuntu-latest

    steps:
      - name: کلون کردن ریپو
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # اجازه‌ی پوش کردن را می‌دهد

      - name: نصب پایتون و وابستگی‌ها
        run: |
          python3 -m pip install --upgrade pip
          pip install ruamel.yaml

      - name: اجرای اسکریپت Python
        run: python3 update_sublist.py

      - name: Commit و Push در صورت تغییر
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # اضافه کردن خروجی‌های Sublist و README و فایل‌های کش
          git add Sublist/*.txt README.md .last_urls.txt .last_template_mtime || true
          # اگر تغییر وجود داشت، کامیت و پوش کن
          if ! git diff --cached --quiet; then
            git commit -m "🔁 ci: به‌روزرسانی Sublist و README لینک‌ها"
            git push
          else
            echo "No changes to commit"
          fi
