name: به‌روزرسانی خودکار لیست‌ها

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز ساعت ۰۰:۰۰ UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
      - name: کلون ریپوزیتوری
        uses: actions/checkout@v3

      - name: نصب پایتون و کتابخانه‌ها
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml urllib3

      - name: اجرای اسکریپت پایتون
        id: run-script
        run: |
          python3 update_sublist.py || exit 1

      - name: کامیت و پوش تغییرات
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔃 به‌روزرسانی خودکار لیست‌ها و خروجی"
          add: |
            *.txt
            Sublist/
