name: به‌روزرسانی Sublist

on:
  schedule:
    - cron: '0 0 * * *'  # اجرای خودکار هر روز ساعت 00:00 UTC
  workflow_dispatch:      # اجرای دستی از GitHub

permissions:
  contents: write

jobs:
  update-sublist:
    runs-on: ubuntu-latest

    steps:
      - name: کلون کردن ریپو
        uses: actions/checkout@v3

      - name: نصب پایتون
        run: |
          python3 -m pip install --upgrade pip

      - name: اجرای اسکریپت Python
        run: python3 update_sublist.py

      - name: Commit و Push در صورت تغییر
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Sublist/ .cache_simple.txt .cache_complex.txt .last_template_mtime README.md
          git diff --cached --quiet || git commit -m "🔁 به‌روزرسانی فایل‌ها و README.md"
          git push
